services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    # This simplified 'depends_on' just waits for the backend 
    # container to be created, which is sufficient.
    depends_on:
      - backend