[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sysinfo = "0.30.11"
actix-cors = "0.7.0"
rand = "0.8.5"
actix-multipart = "0.4"
futures-util = "0.3"

reqwest = "0.11"